name: Issue labeler automation

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  automate-issues-labeling:
    runs-on: ubuntu-latest
    steps:
      - name: Query timeout label
        uses: andymckay/labeler@master
        if: ${{ contains(github.event.issue.title, 'canceling statement due to statement timeout') }}
        with:
          add-labels: "test label"
      - name: Parser Update labeling
        uses: andymckay/labeler@master
        if: ${{ contains(github.event.issue.title, 'parser update') }}
        with:
          add-labels: "enhancement, bug, test label"
          remove-labels: "help wanted"
